# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

favicon:
    logo: log.svg
    icon16: log.svg
    icon32: log.svg
    appleTouchIcon: apple-touch-icon.png
    webmanifest: /site.webmanifest
    visibilitychange: true
    hidden: failure.ico
    showText: (/≧▽≦/)咦！又好了！
    hideText: (●—●)喔哟，崩溃啦！

user:
    name: 程序员贺同学
    first_name: 同学の博客
    last_name: 程序员贺
    email: 1952281585@qq.com
    domain: https://www.herongwei.me
    avatar: /img/avatar.jpg
    describe: 网站简介。
    ruleText: 暂不接受个人博客以外的友链申请，确保您的网站内容积极向上，文章至少30篇，原创70%以上，部署HTTPS。

sidebar:
    typedTextPrefix: I`m
    typedText: ["Backend Developer"]
    social: # 社交地址
        - name: github
          icon: fab fa-github
          url: https://github.com/rongweihe
        - name: gitee
          icon: fab fa-gitlab
          url: https://gitee.com/rongweihe
        - name: zhihu
          icon: fab fa-zhihu
          url: https://www.zhihu.com/people/herongwei
        - name: bilibili
          icon: fab fa-youtube
          url: https://space.bilibili.com/25944369
        - name: weichat
          icon: fab fa-weixin
          url: https://i.328888.xyz/2023/04/09/iciz4J.md.jpeg

top_bars:
    - title: 首页
      url: /
      children:
          - title: archives2
            url: /archives2/
    - title: 归档
      url: /archives/
    - title: 分类
      url: /categories/
    - title: 关于
      url: /categories/

banner:
    index:
        type: video
        bgurl: //cdn.moji.com/websrc/video/autumn20190924.mp4
        bannerTitle: 流水不争先，<br>争的是滔滔不绝。
        bannerText: Hi my new friend!

footer:
  powered:
    enable: true
  beian:
    enable: false
    icp: 
  copyrightYear: 2023
  live_time:
    enable: true
    prefix: footer.tips
    start_time: 04/10/2023 17:00:00
  # custom_text: Hosted by <a href="https://app.netlify.com/" rel="noopener" target="_blank"> Netlify Pages </a>

categorie_card:
    enable: true
    len: 3
    list: ["分类1", "分类2"]

reward:
    enable: true
    comment: 赠人玫瑰，手有余香。
    methods:
        - name: 支付宝
          path: https://www.qq.com
        - name: 微信
          path: https://www.qq.com

toc:
    enable: true
    list_number: true
    max_depth: 3
    min_depth: 1

lazyload:
    enable: true

archive:
    type: less

creative_commons:
    license: by-nc-sa
    language: deed.zh
    post: true
    clipboard: true

assets:
    internal_provider: jsdelivr
    third_party_provider: jsdelivr

cover:
    default: /img/block.jpg
    type: img

post_pagination:
    enable: true
    type: large # large || small

error_img:
    flink: /img/friend_404.gif
    post_page: /img/404.jpg

cdn:
    css:
    js:
        head:
        base:
        async:
        defer:

highlight:
    theme: true
    title: default
    copy: true
    lang: true
    code_word_wrap: fasle
    height_limit: 200 # 超出时，显示折叠按钮

# Site
title: herongweiの博客
subtitle: ''
description: ''
keywords:
author: 贺同学
language: zh-Hans
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme:
  theme: async
  switch: true
  default: style-light

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''
